#Database config File
Schema: 1.0

#The database that you want the home manager to use
home_manager_tablename: player_homes

#The Database information
Database:
  jdbc_connection: jdbc:mysql://1.1.1.1/database_name
  username: uname
  password: pass
