#Database config File
Schema: 1.0

#Main
#The database that the homes system will user
Databases:
  home_manager:
    jdbc_connection: jdbc:mysql://1.1.1.1/Database
    username: usr
    password: pas
    table_name: home