#===========================================# KiloEssentials! MAIN CONFIG #===========================================#
#==-----------------------------== Copyright (c) 2020 KiloCraft, All rights reserved ==-----------------------------==#
#======================[ Licensed under the MIT license | Written by CODY_AI (github: OnBlock) ]======================#
#                                                                                                                     #
#                             NOTE: PLEASE READ THE DESCRIPTION BEFORE DOING ANY CHANGES                              #
#                                                                                                                     #
#==-----------------------------------====-----------------------------------====-----------------------------------==#

#*** Text Formatting
#                    All the string fields support color codes!
#                    You can use '&' as an alternative to the default format character in Minecraft
# Example: "&b I'M AQUA!". Learn more about formatting codes here -> https://minecraft.tools/en/color-code.php

#*** Variables in Strings
#                         Some of the fields support either local or global variables.
# Here is a local variable: {user.displayName}
# And Here is a global variable %server.name%
#                                             You can use the global variables in all of the String fields,
# however local variables get changed in different fields, Like someone's username

#*** Differences between a User and Player
#                                         When a Player joins the server, a user for that player will be created
#                                         A User can be Offline, while the Player has to be Online

#*** Variable Types
#                   User variable group:
# uuid, username, displayName, rankedDisplayName
#                   Player variable group:
# ping, formattedPing, experience
#                   Server variable group:
# name, tps, formattedTps, maxPlayers, onlinePlayers

# Config schema version, Please don't touch this if you don't know what you are doing
schema: 2.0
#
#